// <auto-generated />
namespace MvcProyecto.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _as : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_as));
        
        string IMigrationMetadata.Id
        {
            get { return "201411270406046_as"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
